dist:     bionic
sudo:     required
language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    - os:       osx
      compiler: gcc

    - os:       linux
      compiler: clang

#install:
#    - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - cd unit_tests
    - ctest --output-on-failure
